### PR TITLE
Wasm Execution Contexts now can be created while another thread is running a Wasm module

### LINKED ISSUE #40: Can't create new Wasm Execution Contexts while another thread is running an existing Execution Context
### Describe the bug

In [execution_ctx.rs](https://github.com/vmware-labs/mod_wasm/blob/511096171e9392f9a21b760c48afa32fef843af0/wasm_runtime/src/execution_ctx.rs#L160) `run()` method, the `WASM_RUNTIME_EXECUTIONCTXS` hash map is locked as `read()` during the Wasm module execution. 

This means new threads (new HTTP incoming requests) can't create new execution contexts since that would require exclusive `write()` access.

In a 'normal' scenario, this is suboptimal because it might lead to a situation where Apache is allocating more resources than mod_wasm can leverage.

But in an adverse scenario, if a Wasm module execution takes longer than usual (or hangs up), that might block other incoming requests.

Since CPU-limited executions are not implemented yet (see #9), it would be much better to ensure that the `WASM_RUNTIME_EXECUTIONCTXS` hash map is not locked at all during the Wasm module execution.

### Reproduction steps

1. Create a configuration with two different locations:
   - a) `/intense_task`, whose Wasm execution takes a long time (ie: 10secs)
   - b) `/light_task`, a very simple and immediate task
2. Start up Apache and check both locations works as expected.
3. Then load `/intense_task`, and right after, try loading `/light_task`: It should be obvious that such `/light_task` won't start until `/intense_task` is done.

### Expected behavior

In a mono-thread scenario (ie.: `httpd -X`), new requests are queued and dispatched one by one.
In a multi-threading scenario, new requests shouldn't be delayed because other requests are running the Wasm module.

### Additional context

This issue was reported by @juamedgod, who noticed a wrong behavior while testing a dev version of PHP.wasm whose execution never finished. Thanks for reporting!!

### PR DESCRIPTION
**Pull request by gzurl**
This PR fixes #40: A new thread (from a new incoming HTTP request) could not create a new Wasm execution context while another thread was running a Wasm module. This was only measurable if the execution of the Wasm module was long enough in time or if it took longer than expected (i.e.: I/O issues, infinite loop, etc.). Note that CPU-limited Wasm executions are not implemented yet (see #9).

In the proposed implementation, the executing thread will extract and own its Wasm Execution Context and free the mutex over the Wasm Execution Contexts HashMap. Once is done with execution, the Context will be pushed again into the HashMap.

### CODE REVIEW

File: wasm_runtime/src/execution_ctx.rs [hunk 1]
```diff
@@ -207,6 +197,51 @@ impl WasmExecutionCtx {
...
     }
+
+    // Helper function to insert a Wasm execution context from the HashMap
+    //  
+    // It checks for duplicated `executionctx_id`.
+    // Returns Result<String, String>, with the inserted Wasm execution context id,
+    // otherswise, in case of error the String will contain the reason.
+    //
+    fn try_insert(wasm_executionctx: WasmExecutionCtx) -> Result<String, String> {
+        let executionctx_id = wasm_executionctx.id.clone();
```
Comment (ereslibre) [inline wasm_runtime/src/execution_ctx.rs:208]: I was thinking: why do we need to clone `id`? It's a String, but constructed as a random_hex_id.

For a future improvement: I would change `id` to be a primitive number unsigned type, so that it's `Copy`, and we don't need to clone here and in other places.

File: wasm_runtime/src/execution_ctx.rs [hunk 2]
```diff
@@ -207,6 +197,51 @@ impl WasmExecutionCtx {
...
+
+        // get write access to the WasmExecutionCtx HashMap
+        let mut executionctxs = WASM_RUNTIME_EXECUTIONCTXS.write()
+            .expect("ERROR! Poisoned RwLock WASM_RUNTIME_EXECUTIONCTXS on write()");
```
Comment (ereslibre) [inline wasm_runtime/src/execution_ctx.rs:212]: With `expect` we will be panicking here, I think we want to return an error instead. Following the current API, something like:

```suggestion
let mut executionctxs = WASM_RUNTIME_EXECUTIONCTXS.write().map_err(|e| format!("error: {:?}", e))?;
```

I would do something like that in the rest of the API where we want to return an error, instead of panicking.

As a last comment, the problem with our type `Result<String, String>` is that for consumers, it's very hard to understand what went wrong if something did, they would have to "parse" the error part of the response. Instead, I think we should define something like `Result<String, ErrorType>`, where `ErrorType` is an enum with the possible errors.

I have to admit that mod_wasm is a bit of a special animal, because these "rich" types will be handled in C, and then somehow reported to Apache, so we might want to keep Strings on the errors if we are forwarding them to C and just showing them to the user and not doing any kind of special logic.

**Review by ereslibre — APPROVED** [review]

File: wasm_runtime/src/execution_ctx.rs (hunk 1 above)
Comment (gzurl) [reply wasm_runtime/src/execution_ctx.rs:208]: That's actually great feedback!
Originally, when I started implementing the Wasm executions contexts, I was trying to emulate a Git commit ID, so it was easier to debug.

I think the 'Hex layout' is not really needed anymore and we can use a number instead the String types. I've created #42 to address this 👍

File: wasm_runtime/src/execution_ctx.rs (hunk 2 above)
Comment (gzurl) [reply wasm_runtime/src/execution_ctx.rs:212]: Regarding error types, I agree 100%. Indeed, we mentioned that long time ago and created #4 with that purpose 😄

Comment (gzurl) [reply wasm_runtime/src/execution_ctx.rs:212]: Also, created #43 to deal with poisoned locks.

File: CHANGELOG.md [hunk 3]
```diff
@@ -4,6 +4,14 @@
 
 -
 
+## 0.11.1 (2023/03/30)
```
Comment (gzurl) [inline CHANGELOG.md:7]:
```suggestion
## 0.11.1 (2023/03/31)
```
